name: CI/CD Pipeline
on:
  push:
    branches:
       - Expense-Tracker-App
    paths:
       - '**/CHANGELOG.md'
  
  workflow_dispatch:
    inputs:
      deployVer:
        description: 'Enter Version which you want to deploy (Optional, auto-extracted on push)'
        required: false
        default: ''
      deployEnv:
        description: 'Enter Env where you want to deployed ITG (Optional, auto-extracted on push)'
        required: false
        default: ''

env:
   BUILDENV: 'DEV'
   DEPLOYENV: 'DEV'
   BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
   GitHubToken: ${{ secrets.GITHUB_TOKEN }}

jobs:
 setup-env:
    runs-on: [ label-01 ]
    outputs:
      BUILDENV: ${{ steps.set-env.outputs.BUILDENV }}
      DEPLOYENV: ${{ steps.set-env.outputs.DEPLOYENV }}
    steps:
      - name: Set BUILDENV
        id: set-env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.deployEnv }}" ]]; then
            InputBuildEnv="${{ github.event.inputs.deployEnv }}"
            echo "Using manually provided Deploying Environment: $InputBuildEnv"
            echo "BUILDENV=${InputBuildEnv}" >> $GITHUB_ENV
            echo "BUILDENV=${InputBuildEnv}" >> $GITHUB_OUTPUT
            echo "DEPLOYENV=${DEPLOYENV}" >> $GITHUB_ENV
            echo "DEPLOYENV=${DEPLOYENV}" >> $GITHUB_OUTPUT 
          else
            echo "BUILDENV=${BUILDENV}" >> $GITHUB_ENV
            echo "BUILDENV=${BUILDENV}" >> $GITHUB_OUTPUT
            echo "Auto-extracted version from pipeline: ${BUILDENV}"
            echo "DEPLOYENV=${DEPLOYENV}" >> $GITHUB_ENV
            echo "DEPLOYENV=${DEPLOYENV}" >> $GITHUB_OUTPUT
          fi
          
 Clone:
    runs-on: [ label-01 ]
    needs: [ setup-env ]
    steps:
    
      - name: Cloning the Repo
        run: echo ${{ github.workspace }}
        
      - name: Clear workspace
        run: |
            pwd
            rm -rf ${{ github.workspace }}/*
                
      - name: Checkout code
        run: |
            echo "Branch Name:: ${{ env.BRANCH_NAME }}"
            git clone -b ${{ env.BRANCH_NAME }} https://oauth2:${{ secrets.GITHUBTOKEN }}@github.com/srinithip12/Devops-Engineer.git

 GetChangeLogVersion:
    runs-on: [ label-01 ]
    needs: [ Clone ] 
    outputs:
      CV-Version: ${{ steps.build-step.outputs.CV_NUMBER }}
    steps:   
      - name: Extract CHANGELOG Version (if not provided manually)
        run: |
          pwd
          env_Name=$(echo "${{ env.CLONEBRANCH }}" | sed 's/.*-//' | tr '[:lower:]' '[:upper:]')
          echo Environment Name is $env_Name
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "${{ github.event.inputs.deployEnv }}" && -n "${{ github.event.inputs.deployVer }}" ]]; then
            inputBuildEnv="${{ github.event.inputs.deployEnv }}"
            deployVersion="${{ github.event.inputs.deployVer }}"
            echo "GetChangeLogVersion:Using manually provided version: $deployVersion"
            echo "GetChangeLogVersion:Using manually Deployed Env: $inputBuildEnv"
            echo "CV_NUMBER=${{ github.event.inputs.deployVer }}" >> $GITHUB_OUTPUT
          else
            cd ${{ github.workspace }}/Devops-Engineer
            Current_version=$(grep -o '[0-9]\+\.[0-9]\+\.[0-9]\+' CHANGELOG.md | sed '1q')
            echo "Auto-extracted version from CHANGELOG: $Current_version"
            echo "CV_NUMBER=${Current_version}" >> $GITHUB_OUTPUT
            echo "Auto-extracted version from CHANGELOG: $Current_version"
          fi
          
 Sonarqube:
    runs-on: [ label-01 ]
    needs: [ GetChangeLogVersion ] 
    env:
      CV-Version: ${{ needs.GetChangeLogVersion.outputs.CV-Version }}
    steps:
      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV
      
      - name: SonarQube Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
              cd ${{ github.workspace }}/Devops-Engineer/expense-tracker
              mvn -B clean verify sonar:sonar \
                -Dsonar.projectKey=expense-tracker \
                -Dsonar.projectName="expense-tracker" \
                -Dsonar.projectVersion=$CV_VERSION \
                -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
                -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
                -Dsonar.maven.plugin.version=4.0.0.4121
 Build:
    runs-on: [ label-01 ]
    needs: [ Sonarqube ] 
    env:
       CV-Version: ${{ needs.GetChangeLogVersion.outputs.CV-Version }}
    steps: 

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(dirname $(dirname $(readlink -f $(which java))))" >> $GITHUB_ENV
      
      - name: Build JAR
        run: 
            cd ${{ github.workspace }}/Devops-Engineer/expense-tracker
            && mvn -B clean package -DskipTests

 Deploy:
    runs-on: [ label-01 ]
    needs: [ Build ]
    env:
       CV-Version: ${{ needs.GetChangeLogVersion.outputs.CV-Version }}
    steps:
     - name: Deploy Expense Tracker App locally
       run: |
          echo "Deploying Expense Tracker on local runner..."
          
          # Ensure deployment directory exists
          mkdir -p /opt/expense-tracker
          
          # Copy the built JAR from target
          cp -f /opt/actions-runner/_work/Devops-Engineer/Devops-Engineer/Devops-Engineer/expense-tracker/target/expense-tracker-0.0.1-SNAPSHOT.jar /opt/expense-tracker/expense-tracker.jar
          
          # Stop existing app if running and restart it as gitrunner
          sudo -u gitrunner bash -c '
            PID=$(ps aux | grep "java -jar /opt/expense-tracker/expense-tracker.jar" | grep -v grep | awk "{print \$2}")
            if [ -n "$PID" ]; then
              echo "Stopping existing Expense Tracker... PID=$PID"
              kill $PID
              sleep 1
            fi
          
            echo "Starting Expense Tracker..."
            nohup java -jar /opt/expense-tracker/expense-tracker.jar > /opt/expense-tracker/app.log 2>&1 &
            sleep 1
          '
          
          echo "Expense Tracker deployed successfully!"
          tail -n 20 /opt/expense-tracker/app.log


     - name: Verify the process
       run: |
           echo "Checking if Expense Tracker process is running..."
           ps -ef | grep expense-tracker.jar

     - name: Verify Expense Tracker
       run: |
            echo "Testing API endpoints..."
            echo "GET /api/expenses"
            curl -s http://localhost:8080/api/expenses | jq
